// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB7uLD5-kWwwvMgvWEb-lRF2ECL-nl-fQ',
    appId: '1:346601670649:web:5d5316b7534851aa72df28',
    messagingSenderId: '346601670649',
    projectId: 'flutter-reprep',
    authDomain: 'flutter-reprep.firebaseapp.com',
    databaseURL: 'https://flutter-reprep-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-reprep.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAijD2Kqn0iarLaRvf5E0g51IxJlr0yb7Q',
    appId: '1:346601670649:android:0ff24c047c43052272df28',
    messagingSenderId: '346601670649',
    projectId: 'flutter-reprep',
    databaseURL: 'https://flutter-reprep-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-reprep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb1DDhoYaW1cM6N-xOIchg5i0UwoGLFzg',
    appId: '1:346601670649:ios:409ba3f18ec5a0e372df28',
    messagingSenderId: '346601670649',
    projectId: 'flutter-reprep',
    databaseURL: 'https://flutter-reprep-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-reprep.firebasestorage.app',
    androidClientId: '346601670649-rlnt4k80verk3rg6t2dgmlhrk84368vr.apps.googleusercontent.com',
    iosClientId: '346601670649-1hselqj0g760n6ai1k7qhv5fj2lks810.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb1DDhoYaW1cM6N-xOIchg5i0UwoGLFzg',
    appId: '1:346601670649:ios:409ba3f18ec5a0e372df28',
    messagingSenderId: '346601670649',
    projectId: 'flutter-reprep',
    databaseURL: 'https://flutter-reprep-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-reprep.firebasestorage.app',
    androidClientId: '346601670649-rlnt4k80verk3rg6t2dgmlhrk84368vr.apps.googleusercontent.com',
    iosClientId: '346601670649-1hselqj0g760n6ai1k7qhv5fj2lks810.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB7uLD5-kWwwvMgvWEb-lRF2ECL-nl-fQ',
    appId: '1:346601670649:web:55d33a4f5193bff572df28',
    messagingSenderId: '346601670649',
    projectId: 'flutter-reprep',
    authDomain: 'flutter-reprep.firebaseapp.com',
    databaseURL: 'https://flutter-reprep-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-reprep.firebasestorage.app',
  );

}